### ISSUE TITLE
Easier Install using Python Virtual Environment

### ISSUE THREAD

**Issue by ctcncgr** [tszalay/poreseq#1]
Hi, just a quick comment.  You can build this package using virtual environment without needing to use --user for the pip install or needing super-user permissions.

git clone git://github.com/tszalay/poreseq.git
virtualenv VE-PORESEQ
. VE-PORESEQ/bin/activate
pip install numpy
pip install cython
pip install h5py
cd poreseq
pip install -e .

Also, not everyone has h5py in their system python or local python by default, so I included it in the pip install.

Thanks

**Comment by tszalay** [comment]
Good call, thanks! I've added the virtualenv directions to the README and included h5py in setup.py (numpy and cython are still pre-setup requirements).
