### ISSUE TITLE
Installation Instructions not working

### ISSUE THREAD

**Issue by neurons** [tszalay/poreseq#3]
Machine Configuration: 64-bit x86 machine running Ubuntu 14.04. Following along the instructions and using either of the two specified approaches fails in the last step. Namely, when running `pip install -e . --user` or `sudo pip install -e .` they both fail with this message:

`compilation terminated.`

`error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

More error message details:
```
----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mGtlCc-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/h5py
```

**Comment by tszalay** [comment]
Hi,
Does it work if you first install h5py (`pip install h5py`) before poreseq, using either of the two approaches?

**Comment by neurons** [comment]
Yes, it seems that h5py was necessary. I also installed other packages in addition to h5py and the installation step seems to have worked. Now I'm running into issues  
```File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve  raise DistributionNotFound(reqpkg_resources.DistributionNotFound: pysam>0.8.2 
```

But this is likely due to a problem from using both pip and easy_install to manage packages.
